language: python
python:
- '3.4'
- '3.5'
- '3.6'
install:
- pip install .
- pip install orator
script: python -m pytest
deploy:
  provider: pypi
  user: josephmancuso
  password:
    secure: gBTBSZoMP/r+6NSHvy9EIxiZFqH12S1t8HNRdtGkjrm5A9VxOSg+AGFYjicJmk3g+svIOz4igdNLcxGwduig3+ytmA+VNfOenxNjk728N0P4ilVQOcUYJM5zdletsryUgU1DTkEMvlwj44LvdhCZ/5m1QoSFW6TV0hB4B2JvxPm4Xo3WSbIW8VY0Zy0Mc7Kj7N7stJyP34Bi75j4iLTT27eEAdyPLjC5BAniTXoJWajyq2eianSigA7gANA4Dc2v86E4NBO81EfLT46r/g0pd1H8oj0g/8TxC4xVmc6lXmeBHddGFp2r2YPS8ranR3ZoQcruM+3gIYAIwc7oSa7RPFFhfvmMOSmS2Pp3R+gZC3ks8OPSD8aT7abemZrxDiG8OZJA5M10E5rFuC0FK8Y+Q++Kkro+k/Co/FMXtH+hGddG0jdSY2oUFYC6XZVb3SFWtrkh6jbbbqBJOukrum01J5ZT1T74SRLqWeGDLaU1npC82KwrADo2F64uJ3KFqKST6tEtYaO5qYpoQxRZe0Kz5y9/ZibKiUTCcEKTuS8xzOqv0EL/G1/Wv15YLSvmDz2sspxxD1q8buAqDKX8D/mELh4NUqRjuFVAfFWDamwuM+zVxpuES/DYLRbCd4WRz8CI0TzOO6uQEDq+qAvTjIWp4ddI38fYGa+zAjVJH/R1kBQ=
  on:
    tags: true
    python: 3.6
